on:
  [push]
name: deb11 - GNUstep TRUNK
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-deb11-TRUNK ci-tests/deb11-TRUNK/.
          docker run gnustep-build-ci-deb11-TRUNK
