on:
  [push]
name: deb12 - GNUstep trunk
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-deb12-trunk ci-tests/deb12-trunk/.
          docker run gnustep-build-ci-deb12-trunk
