on:
  [push]
name: GNUstep on Debian 10
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-deb12 ci-tests/deb12/.
          docker run gnustep-build-ci-deb12

