on:
  [push]
name: debsid - GNUstep stable
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-debsid-stable ci-tests/debsid-stable/.
          docker run gnustep-build-ci-debsid-stable
