on:
  [push]
name: debtesting - GNUstep 2021dec
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-debtesting-2021dec ci-tests/debtesting-2021dec/.
          docker run gnustep-build-ci-debtesting-2021dec
