on:
  [push]
name: debtesting - GNUstep trunk
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-debtesting-trunk ci-tests/debtesting-trunk/.
          docker run gnustep-build-ci-debtesting-trunk
