on:
  [push]
name: ubudevel - GNUstep 2023may
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-ubudevel-2023may ci-tests/ubudevel-2023may/.
          docker run gnustep-build-ci-ubudevel-2023may
