on:
  [push]
name: ubudevel - GNUstep stable
jobs:
  testbuild:
    name: Building GNUstep
    runs-on: ubuntu-latest
    steps:
      - name: Check out the build script repository
        uses: actions/checkout@master
      - name: Execute test script
        run: |
          docker build -t gnustep-build-ci-ubudevel-stable ci-tests/ubudevel-stable/.
          docker run gnustep-build-ci-ubudevel-stable
